version: "3.1"
services:
  db:
    image: mongo
    container_name: dataBase
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: datateste
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user

